import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import qrcode from '../src/vendor/qrcode.js';
import jsQR from 'jsqr';
import {fresh,LINE_IDS,encodeTransfer,decodeTransfer,story} from '../src/engine.js';
const browser=await chromium.launch({channel:'msedge',headless:true});
const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{const Original=window.AudioContext;window.AudioContext=class extends Original{constructor(...a){super(...a);window.__testAudio=this;}createGain(){const gain=super.createGain();(window.__testGains??=[]).push(gain);return gain;}};});
await page.goto('http://localhost:4173');await page.locator('[data-panel=settings]:visible').click();await page.locator('#setting-speed').fill('0');await page.locator('#setting-speed').dispatchEvent('input');await page.locator('#close-panel').click();await page.locator('#new-game').click();
await page.locator('#skip').click();await page.waitForTimeout(250);assert.equal(await page.locator('#skip').getAttribute('aria-pressed'),'false');assert.equal(await page.locator('#text').innerText(),story.arrival.lines[1].text);
// A real Web Audio graph is running and produces a non-zero waveform.
await page.evaluate(()=>{window.__analyser=window.__testAudio.createAnalyser();window.__testGains[0].connect(window.__analyser);});await page.waitForTimeout(500);
const audio=await page.evaluate(()=>{const data=new Float32Array(window.__analyser.fftSize);window.__analyser.getFloatTimeDomainData(data);return {state:window.__testAudio.state,peak:Math.max(...data.map(Math.abs))};});assert.equal(audio.state,'running');assert.ok(audio.peak>.00001);
// Backlog, keyboard, auto paused by modal, persistence of settings.
await page.locator('#dialogue').focus();await page.keyboard.press('l');assert.ok(await page.locator('.log-item').count()>=2);await page.keyboard.press('Escape');
await page.locator('#auto').click();await page.locator('#game-screen [data-panel=settings]').click();const before=await page.locator('#text').innerText();await page.waitForTimeout(2200);assert.equal(await page.locator('#text').innerText(),before);await page.locator('#setting-fontSize').fill('30');await page.locator('#setting-fontSize').dispatchEvent('input');await page.locator('#close-panel').click();await page.locator('#auto').click();
for(const viewport of [{width:320,height:568},{width:375,height:667},{width:768,height:1024},{width:1366,height:768}]){await page.setViewportSize(viewport);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.locator('#game-screen [data-panel=save]').click();assert.ok(await page.locator('.slot').first().isVisible());await page.locator('#close-panel').click();}
await page.setViewportSize({width:390,height:844});await page.locator('#menu-button').click();await page.locator('#panel-body').getByRole('button',{name:'引き継ぎ',exact:true}).click();await page.getByRole('button',{name:'コードを発行',exact:true}).click();await page.waitForFunction(()=>document.getElementById('export-code').value.length>0);const code=await page.locator('#export-code').inputValue();const qrData=await page.locator('.qr-wrap img').getAttribute('src');assert.ok(qrData.startsWith('data:image/gif;base64,'));
fs.writeFileSync('test-results/qr.gif',Buffer.from(qrData.split(',')[1],'base64'));await page.locator('#qr-file').setInputFiles('test-results/qr.gif');await page.waitForFunction(()=>document.getElementById('import-code').value.startsWith('NAGI1'));assert.equal(await page.locator('#import-code').inputValue(),code);
await page.screenshot({path:'test-results/transfer-mobile.png'});
// Full progress fits QR and a separate decoder recovers exactly the same data.
const s=fresh();s.trail=LINE_IDS.slice(0,1500);const longCode=await encodeTransfer(s,{seen:LINE_IDS,endings:['voice','ash','shore','glass','storm']});const qr=qrcode(0,'M');qr.addData(longCode);qr.make();const cells=qr.getModuleCount(),scale=5,size=(cells+8)*scale,pixels=new Uint8ClampedArray(size*size*4);pixels.fill(255);for(let y=0;y<cells;y++)for(let x=0;x<cells;x++)if(qr.isDark(y,x))for(let dy=0;dy<scale;dy++)for(let dx=0;dx<scale;dx++){const i=(((y+4)*scale+dy)*size+(x+4)*scale+dx)*4;pixels[i]=pixels[i+1]=pixels[i+2]=0;}const decoded=jsQR(pixels,size,size);assert.equal(decoded.data,longCode);assert.deepEqual((await decodeTransfer(decoded.data)).state,s);
// Take the testimony-first route, initially lose cooperation, then return and recover it.
const branchContext=await browser.newContext(),branch=await branchContext.newPage();branch.on('pageerror',e=>errors.push(e.message));await branch.goto('http://localhost:4173');await branch.locator('[data-panel=settings]:visible').click();await branch.locator('#setting-speed').fill('0');await branch.locator('#setting-speed').dispatchEvent('input');await branch.locator('#close-panel').click();await branch.locator('#new-game').click();
const advanceToChoice=()=>branch.evaluate(()=>{let i=0;while(i++<3000&&document.getElementById('choices').hidden&&document.getElementById('ending-screen').hidden)document.getElementById('dialogue').click();});
const pick=async text=>{await advanceToChoice();await branch.locator('#choices button').filter({hasText:text}).click();};
await pick('目録作り');await pick('館内に残り');await pick('無線');await pick('証言');await pick('皆の前で説明');await pick('事務室');await advanceToChoice();assert.equal(await branch.locator('#choices button').filter({hasText:'時計と再生履歴'}).isDisabled(),true);await pick('調査と聞き直し');await pick('放送設備');await pick('今度は最後まで');await pick('考え直す');await pick('時計と再生履歴');await pick('貸出票と記録');await pick('紬と原本');await pick('最後まで聴く');await advanceToChoice();assert.equal(await branch.locator('#ending-screen').isVisible(),true);await branch.locator('#return-choice').click();assert.equal(await branch.locator('#choices').isVisible(),true);await branchContext.close();
// Blocked browser storage shows fallback; does not prevent reading.
const denied=await browser.newContext(),p=await denied.newPage();await p.addInitScript(()=>{Storage.prototype.setItem=function(){throw new DOMException('Denied','QuotaExceededError');};});await p.goto('http://localhost:4173');await p.locator('#new-game').click();await p.locator('#game-screen [data-panel=save]').click();assert.ok((await p.locator('#panel-body').innerText()).includes('保存できていません'));await denied.close();
// Drafts, tests and Git data stay outside the static server's public routes.
for(const path of ['/docs/spoilers/DESIGN.md','/.git/config','/tests/browser.mjs','/src/..%2fdocs/spoilers/DESIGN.md'])assert.equal((await page.request.get('http://localhost:4173'+path)).status(),404);
assert.deepEqual(errors,[]);fs.writeFileSync('test-results/interaction-summary.json',JSON.stringify({status:'passed',audio,fullProgressCodeLength:longCode.length,qrModules:cells,viewports:4,errors},null,2));console.log('Interaction checks passed: audio, unread skip, auto pause, keyboard, storage denial, QR round trip and image upload, four viewports, private file isolation.');await browser.close();
